### ISSUE TITLE
Chapter headings break at the first markup

### ISSUE THREAD

**Issue by Screwtapello** [zefanja/biblez-ng#17]
First, thanks for writing such a useful app!

I've been reading through Psalms recently (specifically Crosswire's ESV module), and there's a number of places where chapter headings "bleed into" the first verse of the chapter. For example, Psalm 89. With GnomeSword on my desktop machine, it looks something like this (apologies for format approximation):

> # I Will Sing Of The Steadfast Love Of The LORD
>
> ## A Maskil of Ethan the Ezrahite
>
> 1 I will sing of the steadfast love of the LORD, forever;
> with my mouth I will make known your faithfulness to all generations.

Meanwhile, in BibleZ, the result looks more like this:

> # I Will Sing Of The Steadfast Love Of The
> *Lord*
> ## A Maskil
> 1 of Ethan the Ezrahite.I will sing of the steadfast love of the Lord, forever;
> with my mouth I will make known your faithfulness to all generations.

It looks like BibleZ is terminating the heading at the first sign of markup (in the first heading, before "LORD" which is actually supposed to be in small-caps; in the second heading just after "Maskil" where there's a footnote).

**Comment by zefanja** [comment]
Thank you for the report. The filter BibleZ uses to transform OSIS XML to HTML (see filters/osis.js in sword.js) is currently very basic. I'll try to add the code to handle that kind of headings asap.

**Comment by zefanja** [comment]
Fixed in https://github.com/zefanja/swordjs/commit/a105e6aa9dd76b31c714b7bfb582bd5f64bbba8f

I will update the BibleZ app soon, but first I will fix some other issues in swordjs.
