### ISSUE TITLE
Footnotes / cross-references

### ISSUE THREAD

**Issue by mcepl** [zefanja/biblez-ng#19]
With the switch to Firefox on Android (and everything seems to work just fine there; thank you!) I found that in comparison with AndBible the thing I miss the most is not search (and I understand it is a way more complicated) but rather an ability to display footenotes / cross-references. Can BibleZ show them or did I just missed something?

**Comment by zefanja** [comment]
This should be possible. I didn't test it with a lot bibles but it works in ESV for example and in the german version I read. Just open the preferences and enable footnotes and cross-references.

**Comment by mcepl** [comment]
Right, works perfectly. Thank you.
