### ISSUE TITLE
Update of Bible?

### ISSUE THREAD

**Issue by mcepl** [zefanja/biblez-ng#21]
So, I have finally managed to persuade the Sword community (no, it wasn’t that bad) to accept my updated version of CzeBKR. Now, how do I persuade BibleZ to update? When I uninstall/reinstall the bible, it seems to catch the old downloaded version.

**Comment by zefanja** [comment]
I'll fix it this week. Currently there is no way to update a repo.

**Comment by mcepl** [comment]
Did you make any update. Suddenly the app shows just a white screen on my FxAndroid.

**Comment by zefanja** [comment]
No...I haven't finished the update yet.

**Comment by mcepl** [comment]
Hmm, now all apps are doing this.

**Comment by zefanja** [comment]
I submitted the update today.

**Comment by mcepl** [comment]
Yes, it works, but unfortunately I have been forced to uninstall whole app and reinstall, which means I was not able to check the update functionality. Sorry.
